name: Build Release Binaries

on:
  release:
    types:
      - created

jobs:
  build:
    name: Build Release Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.4

      - name: Build kubekey for MacOS(darwin), linux and windows
        run: make

      - name: Checksums (SHA256)
        run: sha256sum kubekey*

      - name: Upload the kubekey binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./kubekey-*-amd64*
          file_glob: true
          body: "Release of kubekey v${{ github.ref }}"
